apiVersion: frontier.singchia.io/v1alpha1
kind: FrontierCluster
metadata:
  labels:
    app.kubernetes.io/name: frontier
    app.kubernetes.io/managed-by: kustomize
  name: frontiercluster-sample
spec:
  # TODO(user): Add fields here
  replica: "1"