apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontier.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "frontier.labels" . | nindent 4 }}
data:
  frontier.yaml: |
{{ .Files.Get "configs/frontier/frontier.yaml" | indent 4 }}