# permissions for end users to edit frontierclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frontiercluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frontier
    app.kubernetes.io/part-of: frontier
    app.kubernetes.io/managed-by: kustomize
  name: frontiercluster-editor-role
rules:
- apiGroups:
  - frontier.singchia.io
  resources:
  - frontierclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frontier.singchia.io
  resources:
  - frontierclusters/status
  verbs:
  - get
