---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - frontier.singchia.io
  resources:
  - frontierclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frontier.singchia.io
  resources:
  - frontierclusters/finalizers
  verbs:
  - update
- apiGroups:
  - frontier.singchia.io
  resources:
  - frontierclusters/status
  verbs:
  - get
  - patch
  - update
